apiVersion: v1
kind: PersistentVolume
metadata:
  name: homeassistant-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  hostPath:
    path: /home/tim/.config/homeassistant
