apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-pvc
spec:
  storageClassName: local
  volumeName: homeassistant-pv
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
